openapi: 3.0.0
info:
  title: Dealstream APIs
  version: 1.0.0
paths:
  /api/opportunity-list:
    get:
      summary: Get the list of all opportunities
      parameters:
        - name: X-API-Key
          in: header
          schema:
            type: string
          required: true
          description: X - API key
      responses:
        '200':
          description: Get the list of all opportunities
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    opportunity:
                      type: string
                    account_name:
                      type: string
                    contact:
                      type: string
                    conversion_probability:
                      type: number
                    created_date:
                      type: string
                      format: date-time
                    deal_stage:
                      type: string
                    enagagement_score:
                      type: number
                    last_action:
                      type: string
                    last_active:
                      type: string
        'default':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/get-meeting-description:
    get:
      summary: Get a meeting description generated by openai model
      parameters:
        - name: X-API-Key
          in: header
          schema:
            type: string
          required: true
          description: API key required for authentication
        - name: meeting_type
          in: query
          schema:
            type: string
          required: true
          description: The type of meeting for which to generate a description
      responses:
        '200':
          description: Generated meeting description
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The generated meeting description
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        'default':
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/get-meeting-objectives:
    get:
      summary: Retrieve meeting objectives
      description: Generates a list of meeting objectives based on the provided sales opportunity information.
      parameters:
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
          description: API key required for authentication
        - name: opportunity_id
          in: query
          required: true
          schema:
            type: string
          description: The ID of the sales opportunity
        - name: meeting_type
          in: query
          required: false # Optional parameters are not marked as required.
          schema:
            type: string
          description: The type of meeting (optional)
        - name: problem_points
          in: query
          required: false # Optional parameters are not marked as required.
          schema:
            type: string
          description: Specific problem points to address (optional)
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  meeting_type:
                    type: string
                  meeting_objectives:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /api/get-action-list-email-message:
    get:
      summary: Get email subject and message
      description: Generates an email subject and message based on the provided action list item information.
      parameters:
        - name: id
          in: query
          description: The ID of the sales note
          required: true
          schema:
            type: string
        - name: X-API-Key
          in: header
          description: API key required for authentication
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  subject:
                    type: string
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/get-stakeholder-email-message:
    get:
      summary: Get stakeholder email subject and message
      description: Generates an email subject and message for a stakeholder based on sales notes and contact information.
      parameters:
        - name: opportunity_id
          in: query
          description: The ID of the sales opportunity
          required: true
          schema:
            type: string
        - name: contact_name
          in: query
          description: The name of the stakeholder contact
          required: true
          schema:
            type: string
        - name: X-API-Key
          in: header
          description: API key required for authentication
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  subject:
                    type: string
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /action-list:
    get:
      summary: Get action list
      description: Retrieves a list of actions from the database.
      parameters:
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
          description: API key required for authentication
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    action_id:
                      type: integer
                    action_name:
                      type: string
                    account_name:
                      type: string
                    opportunity_id:
                      type: string
                    category:
                      type: string
                    category_id:
                      type: integer
                    priority:
                      type: string
                    due_before:
                      type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/get-email-template:
    post:
      summary: Get email template
      description: Generates an email template based on the provided data.
      parameters:
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
          description: API key required for authentication
      requestBody:
        description: Data for generating the email template
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - contact_name
                - problem_points
                - suggested_solutions
              properties:
                contact_name:
                  type: string
                problem_points:
                  type: string
                suggested_solutions:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  subject:
                    type: string
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/prompt:
    post:
      summary: Get pain points, suggested solutions, and actions.
      description: Generates pain points, suggested solutions, and actions.
      parameters:
        - name: X-API-Key
          in: header
          required: true
          schema:
            type: string
          description: API key required for authentication
      requestBody:
        description: Data for generating responses based on sales dialogues and opportunity notes.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model_name
                - opportunity_id
                - messages
                - max_tokens
              properties:
                model_name:
                  type: string
                  description: Name of the language model to use.
                  default: gpt-3.5-turbo-1106
                opportunity_id:
                  type: string
                  description: ID of the opportunity related to the sales note.
                messages:
                  type: array
                  description: List of dialogue messages.
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                        description: Role of the participant in the dialogue (system or user).
                      content:
                        type: string
                        description: Content of the message.
                max_tokens:
                  type: integer
                  description: Maximum number of tokens for the generated response.
                  minimum: 1
                  default: 500
                temperature:
                  type: number
                  description: Temperature to control the randomness of the generated response.
                  minimum: 0
                  maximum: 1
                  default: 0
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  # Additional paths would follow the same conversion pattern...

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string

# Additional components such as request bodies, security schemes, etc., could be defined here as needed.

